# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
#
# See Documentation for more information:
# https://docs.powersync.com/usage/sync-rules
#
# Note that changes to this file are not watched.
# The service needs to be restarted for changes to take effect.

event_definitions:
  # Note this event is only supported for customers on [Team and Enterprise](https://www.powersync.com/pricing) plans.
  write_checkpoints:
    payloads:
      #  This defines where the replicated custom Write Checkpoints should be extracted from
      - SELECT user_id, checkpoint, client_id FROM checkpoints

bucket_definitions:
  global:
    data:
      - select * from Customer
      - select * from Users
      - select * from Categories
      - select * from Products
      - select * from Menu
      - select * from MenuProducts
      - select * from Orders
      - select * from MenuOrder
      - select * from ProductOrder
